--!strict

return table.freeze({
    Version = "2.0.0",
    MaxNPCs = 16,
    ArenaRadius = 64,
    PVPArenaCenterZ = 170,
    PVPArenaHalfWidth = 48,
    PVPArenaHalfDepth = 42,
    PlayerHealth = 100,
    PlayerSpeed = 16,
    AttackCooldown = 0.34,
    ComboReset = 0.9,
    DashCooldown = 1.25,
    DashDistance = 20,
    AttackRange = 11,
    AttackBox = Vector3.new(6, 5, 8),
    WaveIntermission = 5,
    BaseWaveReward = 50,
    ScorePerCredit = 1,
    AIThinkBase = 0.28,
    AIThinkMin = 0.16,
    AIThinkPerWave = 0.0025,
    AITargetRefresh = 0.35,
    AISchedulerStep = 0.08,
    AIErrorLimit = 3,
    RuntimeHealthInterval = 5,
    RuntimeRecoveryCooldown = 6,
    RuntimeRecoveryLimit = 3,
    RankingWriteInterval = 60,
    MaxMissions = 5,
})
