--!strict

return table.freeze({
    Grunt = table.freeze({
        Id = "Grunt",
        Name = "Riftling",
        Health = 40,
        Damage = 8,
        Speed = 10,
        Range = 5,
        Cooldown = 1.2,
        Reward = 10,
        Elite = false,
        Boss = false,
    }),
    Brute = table.freeze({
        Id = "Brute",
        Name = "Breaker",
        Health = 90,
        Damage = 14,
        Speed = 8,
        Range = 6,
        Cooldown = 1.5,
        Reward = 20,
        Elite = false,
        Boss = false,
    }),
    Stalker = table.freeze({
        Id = "Stalker",
        Name = "Stalker",
        Health = 135,
        Damage = 20,
        Speed = 13,
        Range = 5,
        Cooldown = 1,
        Reward = 30,
        Elite = false,
        Boss = false,
    }),
    Elite = table.freeze({
        Id = "Elite",
        Name = "Collision Elite",
        Health = 380,
        Damage = 26,
        Speed = 9,
        Range = 7,
        Cooldown = 1.25,
        Reward = 120,
        Elite = true,
        Boss = false,
    }),
    Boss = table.freeze({
        Id = "Boss",
        Name = "Rift Titan",
        Health = 1100,
        Damage = 40,
        Speed = 7,
        Range = 8,
        Cooldown = 1.4,
        Reward = 300,
        Elite = true,
        Boss = true,
    }),
})
