--!strict
local Players=game:GetService("Players");local DSS=game:GetService("DataStoreService")
local C=require(game.ReplicatedStorage.CBShared.Config);local U=require(game.ReplicatedStorage.CBShared.Util)
local S={};local profiles:{[Player]:any}={};local store=DSS:GetDataStore(C.Data.StoreName)
local function defaults()return{SchemaVersion=1,Coins=0,Inventory={StarterBlade=1},Mastery={Blade=1,Martial=1},Exploration=0,Reputation={FractureDistrict=0},Quest={Id=nil,Progress=0,Target=6,Completed=false},SessionId=nil,SessionTimestamp=nil}end
local function norm(d:any):any local b=defaults();if typeof(d)~="table"then return b end;for k,v in b do if d[k]==nil or typeof(d[k])~=typeof(v)then d[k]=v end end;if typeof(d.Inventory)~="table"then d.Inventory=b.Inventory end;if typeof(d.Mastery)~="table"then d.Mastery=b.Mastery end;if typeof(d.Reputation)~="table"then d.Reputation=b.Reputation end;if typeof(d.Quest)~="table"then d.Quest=b.Quest end;d.Quest.Progress=U.Clamp(tonumber(d.Quest.Progress)or 0,0,math.max(1,tonumber(d.Quest.Target)or 6));d.Quest.Target=math.max(1,tonumber(d.Quest.Target)or 6);d.Quest.Completed=d.Quest.Completed==true;d.SchemaVersion=C.SchemaVersion;return d end
local function key(p:Player)return"Player_"..p.UserId end
local function load(p:Player):any for attempt=1,C.Data.MaxRetries do local ok,res=pcall(function()return store:UpdateAsync(key(p),function(cur)local d=norm(cur);local ts=tonumber(d.SessionTimestamp)or 0;if d.SessionId and d.SessionId~=game.JobId and os.time()-ts<C.Data.SessionTimeoutSeconds then return nil end;d.SessionId=game.JobId;d.SessionTimestamp=os.time();return d end)end);if ok and res then return norm(res)end;task.wait(math.min(2^(attempt-1),8)+math.random())end;return defaults()end
local function save(p:Player):boolean local d=profiles[p];if not d then return true end;local snap=norm(table.clone(d));snap.SessionId=nil;snap.SessionTimestamp=nil;for attempt=1,C.Data.MaxRetries do local ok=pcall(function()store:UpdateAsync(key(p),function(cur)if cur and cur.SessionId and cur.SessionId~=game.JobId then return cur end;return snap end)end);if ok then return true end;task.wait(math.min(2^(attempt-1),8)+math.random())end;return false end
function S.Init()Players.PlayerAdded:Connect(function(p)local d=load(p);profiles[p]=d;local ls=Instance.new("Folder");ls.Name="leaderstats";ls.Parent=p;local c=Instance.new("IntValue");c.Name="Credits";c.Value=d.Coins;c.Parent=ls;p:SetAttribute("QuestProgress",d.Quest.Progress);p:SetAttribute("QuestTarget",d.Quest.Target);p:SetAttribute("QuestCompleted",d.Quest.Completed);p:SetAttribute("Exploration",d.Exploration)end);Players.PlayerRemoving:Connect(function(p)save(p);profiles[p]=nil end);game:BindToClose(function()for _,p in Players:GetPlayers()do save(p)end end);task.spawn(function()while task.wait(C.Data.AutosaveSeconds)do for _,p in Players:GetPlayers()do save(p)end end end)end
function S.Get(p:Player):any?return profiles[p]end
function S.AddCoins(p:Player,n:number)local d=profiles[p];if not d then return end;n=math.floor(n);if n<=0 then return end;d.Coins+=n;local ls=p:FindFirstChild("leaderstats");local c=ls and ls:FindFirstChild("Credits");if c and c:IsA("IntValue")then c.Value=d.Coins end end
function S.StartQuest(p:Player,id:string,target:number)local d=profiles[p];if not d then return end;d.Quest={Id=id,Progress=0,Target=target,Completed=false};p:SetAttribute("QuestId",id);p:SetAttribute("QuestProgress",0);p:SetAttribute("QuestTarget",target);p:SetAttribute("QuestCompleted",false)end
function S.ProgressQuest(p:Player,id:string,n:number):boolean local d=profiles[p];if not d or d.Quest.Id~=id or d.Quest.Completed then return false end;d.Quest.Progress=U.Clamp(d.Quest.Progress+n,0,d.Quest.Target);p:SetAttribute("QuestProgress",d.Quest.Progress);if d.Quest.Progress>=d.Quest.Target then d.Quest.Completed=true;p:SetAttribute("QuestCompleted",true);S.AddCoins(p,50);d.Exploration+=10;d.Reputation.FractureDistrict+=15;p:SetAttribute("Exploration",d.Exploration);return true end;return false end
return S
